version: '3.2'
services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "4000:4000"
    depends_on:
      - db
